version: '3.8'

services:
  todo:
    build: 
      context: .
      dockerfile: dockerfile.todo-service
    volumes:
      - .:/usr/src/app:rw
    ports:
      - 8081:8080
    environment:
      - OTEL_LOG_LEVEL=ERROR
      - NODE_ENV=production
  auth:
    build: 
      context: .
      dockerfile: dockerfile.auth-service
    volumes:
      - .:/usr/src/app:rw
    environment:
      - OTEL_LOG_LEVEL=ERROR
      - NODE_ENV=production
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  jaeger:
    image: jaegertracing/all-in-one
    ports:
        - 16686:16686
        - 14250:14250
    environment:
        COLLECTOR_OTLP_ENABLED: true
  prometheus:
      image: prom/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      volumes:
        - ./prometheus/:/etc/prometheus/
      ports:
        - 9090:9090
  collector:
    image: otel/opentelemetry-collector-contrib
    volumes: 
      - ./collector/collector.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
      - prometheus
